package cmd

import (
	"fmt"
)

func PrintUsage() {
	fmt.Println("Redway - Redroid Container Manager")
	fmt.Println("\nUsage: redway [command] [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  prepare-lxc                    Prepare LXC system (one-time setup)")
	fmt.Println("  init [name] [image]            Initialize container")
	fmt.Println("  start [name]                   Start container")
	fmt.Println("  stop [name]                    Stop container")
	fmt.Println("  restart [name]                 Restart container")
	fmt.Println("  status [name]                  Show container status")
	fmt.Println("  shell [name]                   Enter container shell")
	fmt.Println("  adb-connect [name]             Show ADB connection command")
	fmt.Println("  remove [name]                  Remove container and data")
	fmt.Println("  list                           List all Redway containers")
	fmt.Println("  log [name]                     Show container logs")
	fmt.Println("\nExamples:")
	fmt.Println("  # First time setup:")
	fmt.Println("  redway prepare-lxc                                           # Prepare LXC system")
	fmt.Println("  redway init                                                  # Create default container")
	fmt.Println("  redway start                                                 # Start default container")
	fmt.Println("")
	fmt.Println("  # Multiple containers:")
	fmt.Println("  redway init android1 docker://redroid/redroid:15.0.0_64only-latest")
	fmt.Println("  redway init android2 docker://redroid/redroid:16.0.0_64only-latest")
	fmt.Println("  redway start android1")
	fmt.Println("  redway start android2")
	fmt.Println("  redway list                                                  # List all containers")
	fmt.Println("  redway status android1")
	fmt.Println("  redway adb-connect android1")
	fmt.Println("  redway shell android2")
	fmt.Println("")
	fmt.Println("  # Container management:")
	fmt.Println("  redway stop android1")
	fmt.Println("  redway restart android2")
	fmt.Println("  redway remove android1")
	fmt.Println("  redway log android2")
	fmt.Println("\nDefault container name: redroid")
	fmt.Println("Default image: docker://redroid/redroid:16.0.0_64only-latest")
	fmt.Println("\nNote: Images are fetched from OCI registries via skopeo and converted to LXC containers.")
	fmt.Println("      Each container runs independently with its own data directory and configuration.")
}
